import { Service, Feature, Review, GalleryItem } from "./types";

export const SERVICES: Service[] = [
  {
    id: "haircut",
    name: "Precision Haircut",
    category: "hair",
    price: "₹250 onwards",
    description: "Expert cuts tailored to your face shape and hair type. Includes relaxing hair wash and basic styling.",
    icon: "scissors",
  },
  {
    id: "hair-styling",
    name: "Luxury Styling & Blowdry",
    category: "hair",
    price: "₹499 onwards",
    description: "Signature blowouts, curls, braids, or elegant up-dos for weddings, events, or a polished daily look.",
    icon: "sparkles",
  },
  {
    id: "hair-coloring",
    name: "Global & Highlight Coloring",
    category: "hair",
    price: "₹1,499 onwards",
    description: "Transform your hair with premium global colors, Balayage, Ombré, or seamless highlights using ammonia-free formulas.",
    icon: "palette",
  },
  {
    id: "hair-spa",
    name: "Deep Nourishing Hair Spa",
    category: "hair",
    price: "₹799 onwards",
    description: "Restore hydration, shine, and scalp health with our intense steam therapy and nutrient-rich hair masks.",
    icon: "droplets",
  },
  {
    id: "beard-styling",
    name: "Beard Grooming & Styling",
    category: "grooming",
    price: "₹149 onwards",
    description: "Professional beard trimming, hot towel razor shaving, and premium oil styling to refine your jawline.",
    icon: "user",
  },
  {
    id: "facial",
    name: "Premium Glow Facial",
    category: "skin",
    price: "₹1,199 onwards",
    description: "Rejuvenate your skin with O3+, Gold, or Charcoal deep-infusion facials tailored for hydration and cell renewal.",
    icon: "flower",
  },
  {
    id: "cleanup",
    name: "Deep Pore Cleanup",
    category: "skin",
    price: "₹599 onwards",
    description: "Effective blackhead removal, exfoliation, and a refreshing herbal or fruit mask to restore clear skin.",
    icon: "sparkle",
  },
  {
    id: "bridal-makeup",
    name: "Royal Bridal Makeup",
    category: "makeup",
    price: "₹7,999 onwards",
    description: "Live your dream look with premium HD or Airbrush bridal makeup, hair setting, and draping by master stylists.",
    icon: "crown",
  },
  {
    id: "party-makeup",
    name: "Glam Party Makeup",
    category: "makeup",
    price: "₹2,499 onwards",
    description: "Luminous, high-definition party looks designed to make you stand out at birthdays, receptions, or corporate galas.",
    icon: "gem",
  },
  {
    id: "manicure",
    name: "Spa Manicure",
    category: "nails",
    price: "₹449 onwards",
    description: "Nail shaping, cuticle care, luxurious sugar scrub, hand massage, and long-lasting premium polish.",
    icon: "hand",
  },
  {
    id: "pedicure",
    name: "Therapeutic Spa Pedicure",
    category: "nails",
    price: "₹549 onwards",
    description: "Relaxing warm foot soak, scrub exfoliation, reflexology-inspired foot massage, and custom nail shaping.",
    icon: "activity",
  },
  {
    id: "waxing",
    name: "Sleek Body Waxing",
    category: "skin",
    price: "₹349 onwards",
    description: "Gentle hair removal using premium chocolate, honey, or Rica wax for smooth and glowing skin.",
    icon: "droplet",
  },
  {
    id: "keratin-treatment",
    name: "Keratin Protein Treatment",
    category: "hair",
    price: "₹3,499 onwards",
    description: "Banise frizz and reconstruct damaged hair with intensive hydrolyzed keratin proteins for silk-like smoothness.",
    icon: "shield-check",
  },
  {
    id: "smoothening",
    name: "Silk Smoothening & Straight",
    category: "hair",
    price: "₹3,999 onwards",
    description: "Get perfectly straight, ultra-shiny, and manageable hair with our dermatologically tested hair rebonding.",
    icon: "zap",
  },
  {
    id: "skin-care",
    name: "Advanced Skin Radiance",
    category: "skin",
    price: "₹799 onwards",
    description: "Tan removal, premium bleach, and skin brightening masks to instantly revive tired skin and remove pollution effects.",
    icon: "heart",
  },
];

export const FEATURES: Feature[] = [
  {
    id: "stylists",
    title: "Experienced Stylists",
    description: "Our artists hold certifications in advanced hair styling, color theory, and bridal skincare.",
    icon: "users",
  },
  {
    id: "family",
    title: "Family Friendly",
    description: "Comfortable, warm environment catering to men, women, and kids of all age groups.",
    icon: "heart",
  },
  {
    id: "products",
    title: "Premium Products",
    description: "We use only authorized global brands like L'Oréal Professional, Matrix, O3+, and Lotus Luxury.",
    icon: "award",
  },
  {
    id: "hygiene",
    title: "Hygienic Environment",
    description: "Strict sterilization of tools, disposable sheets, and sanitized workstations for every visit.",
    icon: "shield-check",
  },
  {
    id: "luxury",
    title: "Affordable Luxury",
    description: "Enjoy five-star comfort, complimentary beverages, and premium grooming services without high prices.",
    icon: "sparkles",
  },
  {
    id: "consultation",
    title: "Personalized Consultation",
    description: "Free customized hair and skin diagnosis prior to treatments to understand your exact goals.",
    icon: "message-circle",
  },
  {
    id: "satisfaction",
    title: "Customer Satisfaction",
    description: "We work carefully until you are absolutely delighted with your style, cut, or facial glow.",
    icon: "smile",
  },
  {
    id: "equipment",
    title: "Modern Equipment",
    description: "Equipped with state-of-the-art scalp analyzers, advanced blowdryers, and therapeutic spa beds.",
    icon: "cpu",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "review-1",
    name: "Rahul Sharma",
    rating: 5,
    snippet: "Best salon in Ranchi! The staff is highly professional and the wood-themed interior gives an incredibly luxurious, peaceful ambiance. Got a haircut and hair spa, extremely satisfied with the care they took!",
    date: "2 days ago",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "review-2",
    name: "Priya Singh",
    rating: 5,
    snippet: "Got my bridal makeup done at Hair Mechanic and I couldn't be happier. They used premium international brands and the finish was seamless and natural. The head stylist did a phenomenal job on my hair updo!",
    date: "1 week ago",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "review-3",
    name: "Amit Verma",
    rating: 5,
    snippet: "Extremely clean and hygienic. I visit regularly with my wife and kids. The stylists are highly patient and skilled with children, making haircuts a stress-free experience. Exceptional value for money in Morabadi!",
    date: "2 weeks ago",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "g1",
    title: "Premium Precision Haircut",
    category: "Hair Care",
    imageUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g2",
    title: "Classic Beard Grooming & Trim",
    category: "Grooming",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g3",
    title: "Luxury Hair Coloring & Highlights",
    category: "Color Styling",
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g4",
    title: "Aromatherapy Facial Treatment",
    category: "Skin Care",
    imageUrl: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g5",
    title: "Royal Bridal Styling Session",
    category: "Makeup",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g6",
    title: "Deluxe Nail Spa & Manicure",
    category: "Nails",
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g7",
    title: "Warm Wood-Themed Ambiance",
    category: "Ambiance",
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "g8",
    title: "Expert Hair Spa & Wash",
    category: "Hair Care",
    imageUrl: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&q=80&w=600",
  },
];
